# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:

# These meta hooks check the pre-commit configuration itself.
- repo: meta
  hooks:
  - id: check-useless-excludes

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-added-large-files
  - id: check-toml
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://github.com/psf/black
  rev: 24.4.2
  hooks:
  - id: black

# Commitizen enforces semantic and conventional commit messages.
- repo: https://github.com/commitizen-tools/commitizen
  rev: v3.24.0
  hooks:
  - id: commitizen
    name: Check conventional commit message
    stages: [commit-msg]

# Sort imports.
- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
  - id: isort
    name: Sort import statements

# Upgrade and rewrite Python idioms.
- repo: https://github.com/asottile/pyupgrade
  rev: v3.15.2
  hooks:
  - id: pyupgrade
    name: Upgrade code idioms
    files: ^src/package/|^tests/|setup.py
    args: [--py39-plus]

- repo: https://github.com/pycqa/flake8
  rev: 7.0.0
  hooks:
  - id: flake8

- repo: local
  hooks:
  - id: pylint
    entry: pylint
    language: python
    name: pylint
    require_serial: true
    types: [python]
  - id: mypy
    name: mypy
    entry: mypy
    language: python
    types: [python]
    require_serial: true
  - id: pytest
    always_run: true
    entry: pytest
    language: python
    name: pytest
    pass_filenames: false
